from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.version import APP_VERSION


OUTPUT = ROOT / "version_info.txt"


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = [int(part) for part in version.split(".")]
    if len(parts) > 4:
        raise ValueError(f"Unsupported version format: {version}")
    padded = parts + [0] * (4 - len(parts))
    return padded[0], padded[1], padded[2], padded[3]


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def main() -> None:
    branding = json.loads((ROOT / "branding.json").read_text(encoding="utf-8"))
    product_name = str(branding.get("app_name") or "Turnirium")
    company_name = "Клуб РЕЙД, г. Донецк (https://vk.ru/hema_dn)"
    file_description = "Простая система для проведения ХЕМА турниров, и не только"
    version_tuple = _version_tuple(APP_VERSION)

    text = f"""# UTF-8\n# Generated by tools/generate_version_info.py. Do not edit manually.\nVSVersionInfo(\n  ffi=FixedFileInfo(\n    filevers={version_tuple},\n    prodvers={version_tuple},\n    mask=0x3f,\n    flags=0x0,\n    OS=0x40004,\n    fileType=0x1,\n    subtype=0x0,\n    date=(0, 0)\n  ),\n  kids=[\n    StringFileInfo(\n      [\n        StringTable(\n          '040904B0',\n          [\n            StringStruct('CompanyName', '{_escape(company_name)}'),\n            StringStruct('FileDescription', '{_escape(file_description)}'),\n            StringStruct('FileVersion', '{_escape(APP_VERSION)}'),\n            StringStruct('InternalName', 'Turnirium'),\n            StringStruct('OriginalFilename', 'Turnirium.exe'),\n            StringStruct('ProductName', '{_escape(product_name)}'),\n            StringStruct('ProductVersion', '{_escape(APP_VERSION)}')\n          ]\n        )\n      ]\n    ),\n    VarFileInfo([VarStruct('Translation', [1033, 1200])])\n  ]\n)\n"""
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.name} for version {APP_VERSION}")


if __name__ == "__main__":
    main()
